"use client";
import { useState } from "react";
const Arrow=()=> <span aria-hidden>↗</span>;
export default function Home(){const [email,setEmail]=useState("");const [done,setDone]=useState(false);return <main>
<header><a className="logo" href="#top">SIGNAL<span>°</span></a><nav><a href="#stories">Stories</a><a href="#briefing">Briefing</a><a href="#about">About</a></nav><a className="pill" href="#briefing">Join the signal <Arrow/></a></header>
<div className="ticker"><b>NOW TRACKING</b><p>AI agents · Personal models · Open protocols · Machine identity · The new interface layer</p></div>
<section className="hero" id="top"><div className="kicker"><i>01</i> THE BIG STORY / AUG 24, 2026</div><h1>The web is learning<br/>to <em>act.</em></h1><div className="hero-bottom"><div className="orbit"><i/><b>AGENT</b></div><div><p>AI is moving beyond the chat box. A new generation of agents can plan, browse, negotiate and get things done—and it’s quietly rebuilding the internet around us.</p><a className="button" href="#lead">Read the field guide <Arrow/></a></div></div></section>
<section className="stats"><div><strong>3,466</strong><span>global leaders surveyed on agent adoption</span></div><div><strong>2026</strong><span>the year agents move from pilots to workflows</span></div><div><strong>5 min</strong><span>to understand the shift</span></div></section>
<section className="feature" id="lead"><div className="label"><b>FEATURE</b><span>8 MIN READ</span></div><article><p className="dropcap">For years, software waited for us to click. Agentic software flips that relationship: it watches for intent, assembles a plan, uses tools, and returns with a result. The breakthrough isn’t a smarter chatbot. It’s a new operating model for the web.</p><blockquote>“The interface is no longer a destination. It’s a delegation.”</blockquote><p>Think of an agent as a capable digital operator with boundaries. It can compare flights across tabs, reconcile a spreadsheet, brief a team, or coordinate other specialist agents. The important change is continuity: instead of answering one prompt, the system keeps working toward a goal.</p></article><aside><small>THE STACK</small><ol><li><b>01</b><span><strong>Intent</strong>What you want done</span></li><li><b>02</b><span><strong>Reasoning</strong>How the work is planned</span></li><li><b>03</b><span><strong>Tools</strong>Where action happens</span></li><li><b>04</b><span><strong>Trust</strong>What keeps it bounded</span></li></ol></aside></section>
<section className="stories" id="stories"><div className="title"><p>Beyond the headline</p><h2>Three shifts to watch</h2></div><div className="grid">
{[["coral","A ↔ A","PROTOCOLS · 6 MIN","Agents need a common language","Why open standards for discovery, identity and handoffs could matter as much as the browser once did."],["blue","YOU — AI","IDENTITY · 4 MIN","Your agent will need a passport","Delegated action raises a simple question with difficult answers: who—or what—is authorized to act as you?"],["acid","+ HUMAN","WORK · 7 MIN","The rise of the agent boss","The next management skill may be directing a constellation of tireless, imperfect digital collaborators."]].map(([c,art,meta,t,d])=><article className={`card ${c}`} key={t}><div className="art">{art}</div><small>{meta}</small><h3>{t}</h3><p>{d}</p><a href="#lead">Open story <Arrow/></a></article>)}</div></section>
<section className="briefing" id="briefing"><div><small>THE WEEKLY SIGNAL</small><h2>One idea worth<br/><em>thinking about.</em></h2></div>{done?<div className="success"><b>YOU’RE ON THE LIST.</b><p>Your first Signal arrives next Thursday.</p></div>:<form onSubmit={e=>{e.preventDefault();if(email)setDone(true)}}><label htmlFor="email">A five-minute technology briefing, every Thursday.</label><div><input id="email" type="email" required placeholder="you@somewhere.com" value={email} onChange={e=>setEmail(e.target.value)}/><button aria-label="Subscribe">→</button></div><small>No noise. No breathless hype. Unsubscribe anytime.</small></form>}</section>
<footer id="about"><a className="logo" href="#top">SIGNAL<span>°</span></a><p>Technology, decoded for curious humans.</p><div><a href="#stories">Stories</a><a href="#briefing">Newsletter</a><a href="mailto:hello@signal.example">Contact</a></div><small>© 2026 SIGNAL EDITORIAL</small></footer>
</main>}
